export const residents =[
    {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 20,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 3,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 21,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      }, {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 5,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 23,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 7,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      }, {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 32,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 9,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 13,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 42,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      }, {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 52,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 62,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      }, {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      }, {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      }, {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 2,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      },
      {
        batch: 1,
        contacT_LG:"ikeja",
        countrY_CODE:"string",
        currenT_HOUSE_NUMBER:" string",
        currenT_STREET:" string",
        currenT_TOWN: " string",
        datE_BIRTH: " string",
        duplicatePAN: false,
        emaiL_ADDRESS: " string",
        firstname: " string",
        flaT_NUMBER:" string",
        id: 1,
        lassraId: 72,
        middlename: " string",
        primarY_PHONE_NO: " string",
        registratioN_DATE: " string",
        statE_OF_RESIDENCE: " string",
        status: 3,
        surname:   " string",
      }
]